/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * iTrends API
 * [openapi.json](/api/swagger)
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../mutator';

export type GetApiHello200 = {
  message: string;
  createdAt: string;
};

export type GetApiNotifications200PayloadItem = {
  title?: string;
  date?: string;
};

export type GetApiNotifications200 = {
  statusCode: number;
  message: string;
  payload: GetApiNotifications200PayloadItem[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * iTrends API Version

 * @summary testing
 */
export const getApiHello = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetApiHello200>(
      {url: `/api/hello`, method: 'GET'
    },
      options);
    }
  
/**
 * recent notification list

 * @summary config
 */
export const getApiNotifications = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetApiNotifications200>(
      {url: `/api/notifications`, method: 'GET'
    },
      options);
    }
  
export type GetApiHelloResult = NonNullable<Awaited<ReturnType<typeof getApiHello>>>
export type GetApiNotificationsResult = NonNullable<Awaited<ReturnType<typeof getApiNotifications>>>
